### ISSUE TITLE
Refactor AminoAcidMapping.getAminoAcidMapping(String)

### ISSUE THREAD

**Issue by Verisimilitude11** [Verisimilitude11/DNAnalyzer#191] opened 2022-10-10 21:27 UTC
I've selected [**AminoAcidMapping.getAminoAcidMapping(String)**](https://github.com/Verisimilitude11/DNAnalyzer/blob/43151e8f70d86b468dc676c3f5e3f1bc7a4bdca3/src/main/java/DNAnalyzer/AminoAcidMapping.java#L26-L91) for refactoring, which is a unit of **65** lines of code. Addressing this will make our codebase more maintainable and improve [Better Code Hub](https://bettercodehub.com)'s **Write Short Units of Code** guideline rating! 👍 

Here's the gist of this guideline:
- **Definition** 📖 
Limit the length of code units to 15 lines of code.
- **Why**❓ 
Small units are easier to analyse, test and reuse.
- **How** 🔧 
When writing new units, don't let them grow above 15 lines of code. When a unit grows beyond this, split it in smaller units of no longer than 15 lines.

You can find more info about this guideline in [Building Maintainable Software](http://shop.oreilly.com/product/0636920049159.do). 📖 
 
---- 
ℹ️ To know how many _other_ refactoring candidates need addressing to get a guideline compliant, select some by clicking on the 🔲  next to them. The risk profile below the candidates signals (✅) when it's enough! 🏁 

----
Good luck and happy coding! :shipit: :sparkles: :100:

**Comment by haseeb-xd** [comment] 2022-10-11 20:56
I want to work on this issue, but I am still a new contributor. Can you guide me a bit more how can I refactor that?

**Comment by Verisimilitude11** [comment] 2022-10-11 21:00
Refactor the method into 2 or 3 methods in order to reduce the number of lines.

**Comment by Verisimilitude11** [comment] 2022-10-20 00:56
@haseeb-xd how far are you on this issue? I would also really appreciate it if you would star this repository if you haven't done so yet!

**Comment by Verisimilitude11** [comment] 2022-10-27 06:01
@haseeb-xd I unassigned the issue from you due to a lack of response for more than two weeks. I hope you understand.

**Comment by Verisimilitude11** [comment] 2022-10-27 06:02
@haseeb-xd would you like to join our Discord server: https://discord.gg/5ShCNmyp

**Comment by salahhalkhoums** [comment] 2022-10-27 10:42
Hello @Verisimilitude11 ,
I'm new to contributing to open source and would like this issue assigned to me.

**Comment by Verisimilitude11** [comment] 2022-10-27 14:31
Alright, I assigned the issue to you. Please join our discord server: https://discord.gg/5ShCNmyp

**Comment by salahhalkhoums** [comment] 2022-10-29 13:55
duplicate of #186 already fixed

**Comment by Verisimilitude11** [comment] 2022-10-29 21:41
Got it.

**Closed** 2022-10-29 21:41 UTC
Labels: duplicate
