### ISSUE TITLE
Refactor ProteinFinder.getProtein(String,String)

### ISSUE THREAD

**Issue by Verisimilitude11** [Verisimilitude11/DNAnalyzer#183] opened 2022-10-10 21:27 UTC
I've selected [**ProteinFinder.getProtein(String,String)**](https://github.com/Verisimilitude11/DNAnalyzer/blob/43151e8f70d86b468dc676c3f5e3f1bc7a4bdca3/src/main/java/DNAnalyzer/ProteinFinder.java#L50-L84) for refactoring, which is a unit of **21** lines of code and **5** branch points. Addressing this will make our codebase more maintainable and improve [Better Code Hub](https://bettercodehub.com)'s **Write Simple Units of Code** guideline rating! 👍 

Here's the gist of this guideline:
- **Definition** 📖 
Limit the number of branch points (if, for, while, etc.) per unit to 4.
- **Why**❓ 
Keeping the number of branch points low makes units easier to modify and test.
- **How** 🔧 
Split complex units with a high number of branch points into smaller and simpler ones.

You can find more info about this guideline in [Building Maintainable Software](http://shop.oreilly.com/product/0636920049159.do). 📖 
 
---- 
ℹ️ To know how many _other_ refactoring candidates need addressing to get a guideline compliant, select some by clicking on the 🔲  next to them. The risk profile below the candidates signals (✅) when it's enough! 🏁 

----
Good luck and happy coding! :shipit: :sparkles: :100:

**Comment by garyglatfelter** [comment] 2022-10-15 14:52
I think I can do this but I'm but I'm admittedly weak in understanding some of the core knowledge.
Let me check my understanding with you to ensure I understand correctly. 

"ATG" is a start codon for methionine.
The Stop codon has three possible options: "TAA", "TAG", "TGA".

If there is a sequence like so:

> **atg** ctc gcc cgc gcc ctg ctg ctg tgc gcg gtc ctg gcg ctc agc cat aca ggt gag tac ctg gcg 
> ccg cgc acc ggg gac tcc ggt tcc acg cac ccg ggc aga gtt tcc gct ctg acc tcc tgg gtc tat
> ccc agt act ccg act tct ctc cga ata gag aag cta cgt gac ttg gga aag agc ttg gac cgc **tag**
> agt tcg aaa gaa ctc cgt gga tat tcc agc ttt ccc aca agc act gat cat tat gag cca gtt act
> **taa** ccg atc **tga** gac act ctc acc tcc

Option A) should it return the string between the start codon and the first occurrence of a stop codon?

In this example that would be one string:
> ~~**atg**~~ ctc gcc cgc gcc ctg ctg ctg tgc gcg gtc ctg gcg ctc agc cat aca ggt gag tac ctg gcg 
> ccg cgc acc ggg gac tcc ggt tcc acg cac ccg ggc aga gtt tcc gct ctg acc tcc tgg gtc tat
> ccc agt act ccg act tct ctc cga ata gag aag cta cgt gac ttg gga aag agc ttg gac cgc ~~**tag**~~



Or:


Option B) should it return all possible string between the start codon and all codons? In this example, that would result in these 3 strings.

> ~~**atg**~~ ctc gcc cgc gcc ctg ctg ctg tgc gcg gtc ctg gcg ctc agc cat aca ggt gag tac ctg gcg 
> ccg cgc acc ggg gac tcc ggt tcc acg cac ccg ggc aga gtt tcc gct ctg acc tcc tgg gtc tat
> ccc agt act ccg act tct ctc cga ata gag aag cta cgt gac ttg gga aag agc ttg gac cgc ~~**tag**~~

> ~~**atg**~~ ctc gcc cgc gcc ctg ctg ctg tgc gcg gtc ctg gcg ctc agc cat aca ggt gag tac ctg gcg 
> ccg cgc acc ggg gac tcc ggt tcc acg cac ccg ggc aga gtt tcc gct ctg acc tcc tgg gtc tat
> ccc agt act ccg act tct ctc cga ata gag aag cta cgt gac ttg gga aag agc ttg gac cgc **tag**
> agt tcg aaa gaa ctc cgt gga tat tcc agc ttt ccc aca agc act gat cat tat gag cca gtt act
> ~~**taa**~~


> ~~**atg**~~ ctc gcc cgc gcc ctg ctg ctg tgc gcg gtc ctg gcg ctc agc cat aca ggt gag tac ctg gcg 
> ccg cgc acc ggg gac tcc ggt tcc acg cac ccg ggc aga gtt tcc gct ctg acc tcc tgg gtc tat
> ccc agt act ccg act tct ctc cga ata gag aag cta cgt gac ttg gga aag agc ttg gac cgc **tag**
> agt tcg aaa gaa ctc cgt gga tat tcc agc ttt ccc aca agc act gat cat tat gag cca gtt act
> **taa** ccg atc ~~**tga**~~

**Comment by Verisimilitude11** [comment] 2022-10-16 20:56
Nice! To clarify, only the first occurrence of a string should be returned. Note that a protein has to also have a length that is divisible by 3. Let me know if you have any other questions!

**Comment by garyglatfelter** [comment] 2022-10-17 23:57
Oh I think there's already a PR for this issue. Is this a duplicate of issue #187 ?

**Comment by Verisimilitude11** [comment] 2022-10-18 00:37
Huh, good catch. Do you want to work on this issue instead: https://github.com/Verisimilitude11/DNAnalyzer/issues/103 since you understand DNA science? Thanks for your interest in contributing!

**Closed** 2022-10-18 00:37 UTC
Labels: duplicate, good first issue, hacktoberfest-accepted
